# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20170905_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('award_link', models.URLField(max_length=1000)),
                ('sponsor_org', models.CharField(max_length=1000)),
                ('recurring', models.BooleanField()),
                ('nom_req', models.BooleanField()),
                ('recur_interval', models.CharField(max_length=1000)),
                ('open_date', models.DateTimeField()),
                ('nom_deadline', models.DateTimeField()),
                ('subm_deadline', models.DateTimeField()),
                ('applicant_type', models.CharField(choices=[('staff', 'Staff'), ('faculty_professor', 'Faculty - Professor'), ('tenured_faculty', 'Faculty - Tenured'), ('non_tenured_faculty', 'Faculty - Non-Tenured'), ('graduate_faculty', 'Faculty - Graduate'), ('phd', 'PhD Required'), ('graduate_student', 'Student - Graduate'), ('undergraduate_student', 'Student - Undergraduate'), ('other', 'Other')], default='other', max_length=30)),
                ('additional_info', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('federal', 'Federal Government'), ('state', 'State Government'), ('local', 'Local Government'), ('internal', 'Internal'), ('private_industry', 'Private Industry'), ('other', 'Other')], default='other', max_length=30)),
                ('previous_applicants', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AwardPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(choices=[('unl', 'University of Nebraska - Lincoln'), ('uno', 'University of Nebraska - Omaha'), ('unmc', 'University of Nebraska Medical Center'), ('unk', 'University of Nebraska - Kearney'), ('other', 'Other')], default='uno', max_length=30)),
                ('college', models.CharField(blank=True, max_length=1000)),
                ('dept', models.CharField(blank=True, max_length=1000)),
                ('other_details', models.CharField(blank=True, max_length=1000)),
                ('areas_of_interest', models.ManyToManyField(to='api.AreaOfInterest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StemField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='award',
            name='award_purpose',
            field=models.ManyToManyField(to='api.AwardPurpose'),
        ),
        migrations.AddField(
            model_name='award',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='award',
            name='stem_field',
            field=models.ManyToManyField(to='api.StemField'),
        ),
    ]
