# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171204_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='nom_req',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='award',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
