# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171206_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appType', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='award',
            name='applicant_type',
        ),
        migrations.AddField(
            model_name='award',
            name='applicant_type',
            field=models.ManyToManyField(to='api.ApplicantType'),
        ),
    ]
