# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171208_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='applicant_type',
            field=models.ManyToManyField(null=True, to='api.ApplicantType'),
        ),
        migrations.AlterField(
            model_name='award',
            name='award_purpose',
            field=models.ManyToManyField(null=True, to='api.AwardPurpose'),
        ),
        migrations.AlterField(
            model_name='award',
            name='stem_field',
            field=models.ManyToManyField(null=True, to='api.StemField'),
        ),
    ]
