# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171208_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
