# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180228_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='additional_info',
            new_name='additionalinfo',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='applicant_type',
            new_name='applicanttype',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='award_link',
            new_name='awardlink',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='award_purpose',
            new_name='awardpurpose',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='created_by',
            new_name='createdby',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='created_on',
            new_name='createdon',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='nom_deadline',
            new_name='nomdeadline',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='nom_req',
            new_name='nomreq',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='open_date',
            new_name='opendate',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='recur_interval',
            new_name='recurinterval',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='sponsor_org',
            new_name='sponsororg',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='stem_field',
            new_name='stemfield',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='subm_deadline',
            new_name='submdeadline',
        ),
    ]
