# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180228_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='areas_of_interest',
            new_name='areasofinterest',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='other_details',
            new_name='otherdetails',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
