# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180228_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicanttype',
            old_name='appType',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='areaofinterest',
            old_name='area',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='awardpurpose',
            old_name='purpose',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stemfield',
            old_name='field',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='award',
            name='applicanttype',
            field=models.ManyToManyField(blank=True, to='api.Applicanttype'),
        ),
        migrations.AlterField(
            model_name='award',
            name='awardpurpose',
            field=models.ManyToManyField(blank=True, to='api.Awardpurpose'),
        ),
        migrations.AlterField(
            model_name='award',
            name='stemfield',
            field=models.ManyToManyField(blank=True, to='api.Stemfield'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areasofinterest',
            field=models.ManyToManyField(blank=True, to='api.Areaofinterest'),
        ),
    ]
