# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180228_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='applicanttype',
        ),
        migrations.RemoveField(
            model_name='award',
            name='awardpurpose',
        ),
        migrations.RemoveField(
            model_name='award',
            name='stemfield',
        ),
        migrations.AddField(
            model_name='award',
            name='applicanttypes',
            field=models.ManyToManyField(blank=True, null=True, related_name='awards', to='api.Applicanttype'),
        ),
        migrations.AddField(
            model_name='award',
            name='awardpurposes',
            field=models.ManyToManyField(blank=True, null=True, related_name='awards', to='api.Awardpurpose'),
        ),
        migrations.AddField(
            model_name='award',
            name='stemfields',
            field=models.ManyToManyField(blank=True, null=True, related_name='awards', to='api.Stemfield'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areasofinterest',
            field=models.ManyToManyField(blank=True, to='api.Areaofinterest'),
        ),
    ]
