# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180228_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='applicanttypes',
            field=models.ManyToManyField(blank=True, related_name='awards', to='api.Applicanttype'),
        ),
        migrations.AlterField(
            model_name='award',
            name='awardpurposes',
            field=models.ManyToManyField(blank=True, related_name='awards', to='api.Awardpurpose'),
        ),
        migrations.AlterField(
            model_name='award',
            name='stemfields',
            field=models.ManyToManyField(blank=True, related_name='awards', to='api.Stemfield'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areasofinterest',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='api.Areaofinterest'),
        ),
    ]
