# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180302_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='source',
        ),
        migrations.AlterField(
            model_name='award',
            name='applicanttypes',
            field=models.ManyToManyField(blank=True, related_name='awards', to='api.Applicanttype'),
        ),
        migrations.AlterField(
            model_name='award',
            name='awardpurposes',
            field=models.ManyToManyField(blank=True, related_name='awards', to='api.Awardpurpose'),
        ),
        migrations.AlterField(
            model_name='award',
            name='stemfields',
            field=models.ManyToManyField(blank=True, related_name='awards', to='api.Stemfield'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areasofinterest',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='api.Areaofinterest'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
