# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20180302_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='applicanttypes',
            field=models.ManyToManyField(blank=True, related_name='awards', to='api.Applicanttype'),
        ),
        migrations.AlterField(
            model_name='award',
            name='awardpurposes',
            field=models.ManyToManyField(blank=True, related_name='awards', to='api.Awardpurpose'),
        ),
        migrations.AlterField(
            model_name='award',
            name='recurinterval',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='award',
            name='sponsororg',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='award',
            name='stemfields',
            field=models.ManyToManyField(blank=True, related_name='awards', to='api.Stemfield'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areasofinterest',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='api.Areaofinterest'),
        ),
    ]
